# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Compile debug and test sources"
  lane :compile do
    gradle(task: "compileDebugSources", project_dir: "android")
    gradle(task: "compileDebugUnitTestSources", project_dir: "android")
    gradle(task: "compileDebugAndroidTestSources", project_dir: "android")
  end

  desc "Assemble APKs"
  lane :assemble do
    gradle(
        task: "build",
        project_dir: "android")
  end
end