name: Build
on:
  pull_request:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Vue.JS app
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: npm ci
        run: npm run build
      - name: Sync build with Android
        run: npm run sync
      - name: Copy resources to Android
        run: npm run icons