name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Vue.JS app
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci && npm run build
      - run: npm run sync
      - run: npm run icons
      - name: Set gradle permissions
        run: chmod +x ./android/gradlew
      - name: Build Android app
        run: ./android/gradlew buildDebug
